--------------------------------------------------------
--  File created - Wednesday-November-08-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View ADMIN_LOGIN_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "MKD"."ADMIN_LOGIN_VIEW" ("UNAME", "PASS") AS 
  SELECT uname, pass from admin_master
;
--------------------------------------------------------
--  DDL for View CANTEEN_LOGIN_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "MKD"."CANTEEN_LOGIN_VIEW" ("UNAME", "PASS") AS 
  SELECT uname, pass from canteen_master
;
--------------------------------------------------------
--  DDL for View STUDENT_LOGIN_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "MKD"."STUDENT_LOGIN_VIEW" ("UNAME", "PASS") AS 
  SELECT uname, pass from student_master
;
--------------------------------------------------------
--  DDL for Table ADMIN_MASTER
--------------------------------------------------------

  CREATE TABLE "MKD"."ADMIN_MASTER" 
   (	"ADMIN_ID" NUMBER(*,0), 
	"PASS" NVARCHAR2(50), 
	"UNAME" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CANTEEN_MASTER
--------------------------------------------------------

  CREATE TABLE "MKD"."CANTEEN_MASTER" 
   (	"CANTEEN_ID" NUMBER(*,0), 
	"WALLET1" NUMBER(10,2) DEFAULT ( 0 ), 
	"OPEN_TIME" TIMESTAMP (9) DEFAULT ( SYSDATE ), 
	"CLOSE_TIME" TIMESTAMP (9) DEFAULT ( SYSDATE ), 
	"RATING" NUMBER(5,1) DEFAULT ( 0.0 ), 
	"ORDER_LIMIT" NUMBER(*,0) DEFAULT ( 0 ), 
	"PH_NO" NUMBER(*,0), 
	"UNAME" NVARCHAR2(50), 
	"PASS" NVARCHAR2(50), 
	"EMAIL" NVARCHAR2(50), 
	"CANTEEN_NAME" NVARCHAR2(50), 
	"FEEDBACK_COUNT" NUMBER(*,0) DEFAULT ( 0 )
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CANTEEN_NOTIFICATION_MASTER
--------------------------------------------------------

  CREATE TABLE "MKD"."CANTEEN_NOTIFICATION_MASTER" 
   (	"CANTEEN_ID" NUMBER(*,0), 
	"NOT_DATE" TIMESTAMP (9) DEFAULT ( SYSDATE ), 
	"MESSAGE" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOOD_MASTER
--------------------------------------------------------

  CREATE TABLE "MKD"."FOOD_MASTER" 
   (	"FOOD_ITEM_ID" NUMBER(*,0), 
	"NAME" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MENU_MASTER
--------------------------------------------------------

  CREATE TABLE "MKD"."MENU_MASTER" 
   (	"CANTEEN_ID" NUMBER(*,0), 
	"FOOD_ITEM_ID" NUMBER(*,0), 
	"QTY" NUMBER(*,0) DEFAULT ( 0 ), 
	"RATE" NUMBER(*,0) DEFAULT ( 0 )
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_DETAIL
--------------------------------------------------------

  CREATE TABLE "MKD"."ORDER_DETAIL" 
   (	"ORDER_ID" NUMBER(*,0), 
	"FOOD_ITEM_ID" NUMBER(*,0), 
	"QTY" NUMBER(*,0) DEFAULT ( 0 ), 
	"RATE" NUMBER(18,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_HEADER
--------------------------------------------------------

  CREATE TABLE "MKD"."ORDER_HEADER" 
   (	"ORDER_ID" NUMBER(*,0), 
	"STU_ID" NUMBER(*,0), 
	"CANTEEN_ID" NUMBER(*,0), 
	"AMOUNT" NUMBER(*,0), 
	"STATUS" NVARCHAR2(50), 
	"ORDER_DATE" TIMESTAMP (9) DEFAULT (sysdate)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDENT_MASTER
--------------------------------------------------------

  CREATE TABLE "MKD"."STUDENT_MASTER" 
   (	"ID" NUMBER(*,0), 
	"NAME" NVARCHAR2(50), 
	"COLLEGE" NVARCHAR2(50), 
	"UNAME" NVARCHAR2(50), 
	"PASS" NVARCHAR2(50), 
	"WALLET" NUMBER(*,0), 
	"BDATE" DATE DEFAULT ( sysdate ), 
	"PH_NO" NUMBER(*,0) DEFAULT ( 0 ), 
	"EMAIL" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDENT_NOTIFICATION_MASTER
--------------------------------------------------------

  CREATE TABLE "MKD"."STUDENT_NOTIFICATION_MASTER" 
   (	"STUDENT_ID" NUMBER(*,0), 
	"NOT_DATE" TIMESTAMP (9) DEFAULT ( SYSDATE ), 
	"MESSAGE" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence QCSEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "MKD"."QCSEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Trigger TR_CHK_AMT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MKD"."TR_CHK_AMT" BEFORE
    INSERT OR UPDATE ON order_header
    FOR EACH ROW
DECLARE
    tmp_wallet   NUMBER(5);
BEGIN
    SELECT
        wallet
    INTO
        tmp_wallet
    FROM
        student_master
    WHERE
        id =:new.stu_id;

    IF
        ( tmp_wallet < :new.amount )
    THEN
        ROLLBACK;
    END IF;
END;
/
ALTER TRIGGER "MKD"."TR_CHK_AMT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_ORDERING
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MKD"."TR_ORDERING" AFTER
    INSERT ON order_detail
    FOR EACH ROW
BEGIN
    UPDATE order_header
        SET
            amount = amount + (:new.qty *:new.rate )
    WHERE
        order_id =:new.order_id;

END;
/
ALTER TRIGGER "MKD"."TR_ORDERING" ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_DETAIL
--------------------------------------------------------

  ALTER TABLE "MKD"."ORDER_DETAIL" MODIFY ("RATE" NOT NULL ENABLE);
  ALTER TABLE "MKD"."ORDER_DETAIL" MODIFY ("FOOD_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "MKD"."ORDER_DETAIL" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT_MASTER
--------------------------------------------------------

  ALTER TABLE "MKD"."STUDENT_MASTER" ADD CONSTRAINT "email1_const" CHECK (
    email LIKE '%_@_%._%'
) ENABLE;
  ALTER TABLE "MKD"."STUDENT_MASTER" ADD CONSTRAINT "PH1_CONST" CHECK (regexp_like (ph_no, '^[9][1][789]\d{9}$')) ENABLE;
  ALTER TABLE "MKD"."STUDENT_MASTER" ADD PRIMARY KEY ("UNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MKD"."STUDENT_MASTER" MODIFY ("BDATE" NOT NULL ENABLE);
  ALTER TABLE "MKD"."STUDENT_MASTER" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "MKD"."STUDENT_MASTER" MODIFY ("UNAME" NOT NULL ENABLE);
  ALTER TABLE "MKD"."STUDENT_MASTER" MODIFY ("COLLEGE" NOT NULL ENABLE);
  ALTER TABLE "MKD"."STUDENT_MASTER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MKD"."STUDENT_MASTER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_HEADER
--------------------------------------------------------

  ALTER TABLE "MKD"."ORDER_HEADER" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MKD"."ORDER_HEADER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MKD"."ORDER_HEADER" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "MKD"."ORDER_HEADER" MODIFY ("CANTEEN_ID" NOT NULL ENABLE);
  ALTER TABLE "MKD"."ORDER_HEADER" ADD CONSTRAINT "STATUS_CHECK" CHECK (status IN ('placed', 'prepared', 'can_request', 'can_app', 'can_deny')) ENABLE;
  ALTER TABLE "MKD"."ORDER_HEADER" MODIFY ("STU_ID" NOT NULL ENABLE);
  ALTER TABLE "MKD"."ORDER_HEADER" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOOD_MASTER
--------------------------------------------------------

  ALTER TABLE "MKD"."FOOD_MASTER" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MKD"."FOOD_MASTER" ADD PRIMARY KEY ("FOOD_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MKD"."FOOD_MASTER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MKD"."FOOD_MASTER" MODIFY ("FOOD_ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN_MASTER
--------------------------------------------------------

  ALTER TABLE "MKD"."ADMIN_MASTER" ADD PRIMARY KEY ("ADMIN_ID", "UNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MKD"."ADMIN_MASTER" MODIFY ("UNAME" NOT NULL ENABLE);
  ALTER TABLE "MKD"."ADMIN_MASTER" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "MKD"."ADMIN_MASTER" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT_NOTIFICATION_MASTER
--------------------------------------------------------

  ALTER TABLE "MKD"."STUDENT_NOTIFICATION_MASTER" MODIFY ("MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "MKD"."STUDENT_NOTIFICATION_MASTER" MODIFY ("NOT_DATE" NOT NULL ENABLE);
  ALTER TABLE "MKD"."STUDENT_NOTIFICATION_MASTER" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANTEEN_NOTIFICATION_MASTER
--------------------------------------------------------

  ALTER TABLE "MKD"."CANTEEN_NOTIFICATION_MASTER" MODIFY ("MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "MKD"."CANTEEN_NOTIFICATION_MASTER" MODIFY ("NOT_DATE" NOT NULL ENABLE);
  ALTER TABLE "MKD"."CANTEEN_NOTIFICATION_MASTER" MODIFY ("CANTEEN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU_MASTER
--------------------------------------------------------

  ALTER TABLE "MKD"."MENU_MASTER" ADD PRIMARY KEY ("CANTEEN_ID", "FOOD_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MKD"."MENU_MASTER" MODIFY ("FOOD_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "MKD"."MENU_MASTER" MODIFY ("CANTEEN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANTEEN_MASTER
--------------------------------------------------------

  ALTER TABLE "MKD"."CANTEEN_MASTER" ADD PRIMARY KEY ("UNAME", "CANTEEN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MKD"."CANTEEN_MASTER" ADD CONSTRAINT "email_const" CHECK (
    email LIKE '%_@_%._%'
) ENABLE;
  ALTER TABLE "MKD"."CANTEEN_MASTER" MODIFY ("CANTEEN_NAME" NOT NULL ENABLE);
  ALTER TABLE "MKD"."CANTEEN_MASTER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MKD"."CANTEEN_MASTER" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "MKD"."CANTEEN_MASTER" MODIFY ("UNAME" NOT NULL ENABLE);
  ALTER TABLE "MKD"."CANTEEN_MASTER" ADD CONSTRAINT "PH_CONST" CHECK (regexp_like (PH_NO, '^[9][1][789]\d{9}$')) ENABLE;
  ALTER TABLE "MKD"."CANTEEN_MASTER" MODIFY ("PH_NO" NOT NULL ENABLE);
  ALTER TABLE "MKD"."CANTEEN_MASTER" MODIFY ("CANTEEN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MENU_MASTER
--------------------------------------------------------

  ALTER TABLE "MKD"."MENU_MASTER" ADD FOREIGN KEY ("FOOD_ITEM_ID")
	  REFERENCES "MKD"."FOOD_MASTER" ("FOOD_ITEM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_DETAIL
--------------------------------------------------------

  ALTER TABLE "MKD"."ORDER_DETAIL" ADD CONSTRAINT "FD_FK" FOREIGN KEY ("FOOD_ITEM_ID")
	  REFERENCES "MKD"."FOOD_MASTER" ("FOOD_ITEM_ID") ENABLE;
  ALTER TABLE "MKD"."ORDER_DETAIL" ADD CONSTRAINT "OD_FK" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "MKD"."ORDER_HEADER" ("ORDER_ID") ENABLE;
